# from hashlib import new
from flashtext import KeywordProcessor
keyword_processor = KeywordProcessor()

# keyword dictionary to add all at once
# {'clean_name': ['list of unclean names']}
keyword_dict = {
    "abstract": ["abstrait"],
    "arguments": [],
    "async": [],
    "await": ['attend', "espera"],
    "boolean": ["booléen", "boolean", "booleano"],
    "break": ["brise", "rompea"],
    "byte": ["octet"],
    "case": ["cas", "caso"],
    "catch": ["reprend", "atrapa"],
    "char": [],
    "const": [],
    "continue": ["poursuit", "sigue"],
    "debugger": ["debogue", "débogue"],
    "default": ["defaut", "défaut", "defecto"],
    "delete": ["supprime", "borra"],
    "do": ["effectue", "haga"],
    "double": ["doble"],
    "else": ["sinon", "otro caso"],
    "eval": [],
    "false": ["faux", "falso"],
    "final": [],
    "finally": ["enfin", "por fin"],
    "float": ['flottant', "flotante"],
    "for": ['pour', "para"],
    "function": ['fonction', "funcion", "función"],
    "goto": [],
    "if": ['si'],
    "implements": ["implementa"],
    "in": ["dans", "en"],
    "instanceof": ["instancede", "instanciade"],
    "int": [],
    "interface": ["interfaz"],
    "let": ["laisse", "deja"],
    "long": ["largo"],
    "native": ["nativo"],
    "new": ["nouveau", "nuevo"],
    "null": ["nul", "nulo"],
    "package": ["paquet", "paquete"],
    "private": ["prive", "privé", "privado"],
    "protected": ["protege", "protegé", 'protégé', 'protegido'],
    "public": ["publico", "pública"],
    "return": ['retourne', "vuelva"],
    "short": ["corto", "court"],
    "static": ['statique', "estático"],
    "switch": ['change', "cambia"],
    "synchronized": [],
    "this": ['celui', "esto"],
    "throw": ['lance', "lanza"],
    "throws": [],
    "transient": [],
    "true": ['vrai', "verdadero"],
    "try": ['essaie', "intenta"],
    "typeof": ['typede', "typode"],
    "var": [],
    "void": ['vide', "vacío", "vacio"],
    "volatile": [],
    "while": ["tant", "mientras"],
    "with": ["avec", "con"],
    "yield": ["cede", "cède"],
    "class": ['classe', "clase"],
    "enum": ['énum',],
    "export": ['exporte', 'exporta'],
    "extends": ['étend', 'etend', "extiende"],
    "import": ['importe', "importa"],
    "super": [],
 }
 
built_in_dict = {
    "charAt": ["charIndex", "carIndice"],
    "charCodeAt": ["charCodeIndex", "carCodigoIndice", "carCódigoIndice"],
    "concat": ["enchaîne", "enchaine", "concatena"],
    "every": ["chaque", "cada"],
    "filter": ["filtre", 'filtra'],
    "forEach": ["pourChacun", "paraCada"],
    "indexOf": ["indexDe", "indiceDe", "índiceDe"],
    "join": ["joint", "une"],
    "lastIndexOf": ["dernierIndexDe", "ultimoIndiceDe", "últimoIndiceDe"],
    "length": ["longeur", "largo"],
    "map": ["caractérise", "caracterise", "mapa"],
    "match": ["compare", "iguala"],
    "pop": ["enlève", "enleve", "retira"],
    "push": ["ajoute", "anade", "añade"],
    "reduce": ["réduit", "reduit", "re"],
    "reduceRight": ["réduitDroit", "reduitDroit"],
    "replace": ["remplace", "reemplace"],
    "reverse": ["renverse"],
    "search": ["cherche", "busca"],
    "shift": ["déplace", "deplace"],
    "slice": ["coupe"],
    "some": ["quelques"],
    "sort": ["trie"],
    "split": ["sépare", "separe"],
    "substr": [],
    "substring": [],
    "toLowerCase": ["enMiniscule"],
    "toUpperCase": ["enMajuscule"],
    "valueOf": ["valeurDe"],
    "console.log": ["console.enr", "consola.anota"]
}
 

# adding list of keywords
def replacing_keywords(js_str):
    keyword_processor.add_keywords_from_dict(keyword_dict)
    # replacing keywords
    new_str = keyword_processor.replace_keywords(js_str)
    return new_str